### ISSUE TITLE
Releases not found

### ISSUE THREAD

**Issue by maximevince** [AmigaPorts/a500hdd#7]
The `README.md` says:

> Binary and gerber files are only packaged in releases. For gerbers see board/gerber directory. For device/software binaries see software/bin and device/bin directories.

However, no releases are to be found: https://github.com/AmigaPorts/a500hdd/releases

**Comment by tehKaiN** [comment]
ah yes, they've never materialized because my gerbers used for first and only batch were kinda bad - perforations used to break boards have become metalized.

I'll try to fix it soon!

**Comment by tehKaiN** [comment]
apparently I had the fix all along and even gerbers were already baked, probably did that for someone else a long time ago. No tested by me though!

**Comment by maximevince** [comment]
Awesome, thanks!
